# Generated by Django 5.0.7 on 2024-08-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_feature_image_course_techs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='feature_image',
            new_name='featured_img',
        ),
    ]
