# Generated by Django 5.0.7 on 2024-09-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_courserating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserating',
            old_name='review_tiom',
            new_name='review_time',
        ),
    ]
