# Generated by Django 5.0.7 on 2024-09-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_courserating_options_alter_courserating_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={},
        ),
    ]
