# Generated by Django 5.0.7 on 2024-10-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': '10. Notifications'},
        ),
        migrations.AlterModelOptions(
            name='studentassignment',
            options={'verbose_name_plural': '9. Student Assignments'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notif_text',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_for',
            field=models.CharField(max_length=200, verbose_name='Notification For'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifiread_status',
            field=models.BooleanField(default=False, verbose_name='Notification Status'),
        ),
    ]
