# Generated by Django 5.0.7 on 2024-10-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_notification_student_notification_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Student',
            new_name='student',
        ),
    ]
