# Generated by Django 5.0.7 on 2024-10-12 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_attemptquiz_question_attemptquiz_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquiz',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizquestions'),
        ),
    ]
